config/routes.rb
Rails.application.routes.draw do
  # если POST-запрос на сервере придет по адресу /messages
  # его нужно отправить к методу create контроллера messages
  
  #post '/messages', to: 'messages#create'
  #patch '/messages/:id', to: 'messages#update'
  #delete '/messages/:id', to: 'messages#destroy'

  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # skip_before_action :verify_authenticity_token  
  before_action :set_message, only: %i[update show destroy edit]
  def create
    # передаем в метод 2 именованных параметра
    #message = Message.create(
    #  body: params[:message][:body],
    #  user_id: params[:message][:user_id]
    #)
    # чтобы злоумышленник не мог изменить данные
    # permitted? - понимает, можно ли с этими параментрами
    # отправлять запрос в БД (защита от дурака)
    # приватный метод message_params
    message = Message.create(message_params)

    redirect_to message_path(message)
    #render text: "Ваш запрос обработан"
  end
  
  # обновление вопроса, который мы найдем по этому id
  def update
    #@message = Message.find(params[:id])
    @message.update(
      body: params[:message][:body],
      user_id: params[:message][:user_id]
    )

    redirect_to message_path(@message)
  end

  def destroy
    #@message = Message.find(params[:id])
    @message.destroy
    redirect_to messages_path
  end

  def show
    # собака нужна, чтобы переменная была доступна в шаблоне
    #@message = Message.find(params[:id])
  end

  def index
    # множественное число! html each 
    @messages = Message.all
  end

  def new 
    # знает только структуру вопроса, пока еще не сохранена в базе
    @message = Message.new
  end

  def edit 
  end

  private 
  def message_params
    params.require(:message).permit(:body, :user_id)
  end

  def set_message
    @message = Message.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Start</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/edit.html.erb
<div class = "container">
    <h2 class="title-lg mb"> Редактирование письма <%= @message.id %> </h2>
    <%= form_with model: @message do |form| %>
        <p><%= form.label :body, 'Текст письма' %></p>
        <p><%= form.text_area :body, rows:5 %></p>
        
        <p class ="mt"><%= form.label :user_id %></p>
        <p><%= form.text_field :user_id %></p>
        
        <p class ="mt"><%= form.submit 'Сохранить' %></p>
    <% end %>
</div>

app/views/messages/index.html.erb
<div class = "container">
    <h2 class="title-lg mb">Все письма</h2>

    <% @messages.each do |message| %>
        <!-- <p>Письмо <%= message.id %></p> -->
        <!-- <p> <%= link_to "Письмо #{message.id}","/messages/#{message.id}" %></p> -->
        <!-- <p> <%= link_to "Письмо #{message.id}",message_path(message.id) %></p> -->
        <p class="mb-sm"> <%= link_to "Письмо #{message.id}",message_path(message) %></p> 
    <% end %>

    <p class="mt"><%= link_to "Создать новое письмо", new_message_path %></p>
</div>

app/views/messages/new.html.erb
<div class = "container">
    <h2 class="title-lg mb">Написать письмо</h2>

    <!-- <form action = "/messages" method="POST">                 -->
    <!--   <p><label for="message[body]">Текст письма</label></p>  -->
    <!--   <p><textarea name = "message[body]"></textarea></p>     -->
    <!--   <p><label for="message[user_id]">User ID</label></p>    -->
    <!--   <p> <input type="number" name = "message[user_id]"> </p>--> 
    <!--   <p><input type = "submit" value = "Создать"></p>        -->
    <!-- </form> -->

    <%= form_with model: @message do |form| %>
        <p><%= form.label :body, 'Текст письма' %></p>
        <p><%= form.text_area :body, rows:5 %></p>
        
        <p class ="mt"><%= form.label :user_id %></p>
        <p><%= form.text_field :user_id %></p>
        
        <p class ="mt"><%= form.submit 'Создать' %></p>
    <% end %>
</div>

app/views/messages/show.html.erb
<div class = "container">
    <h2 class="title-lg mb"> Письмо <%= @message.id%></h2>
    <p class="mb-sm"> <%= @message.body%> </p>
    <p>user_id: <b><%= @message.user_id%></b></p>
    <!-- <p> <%= link_to "Вернуться ко всем отправленным письмам", "/messages"%> </p> -->


    <p class="mt"> 
        <%= link_to fa_icon('pencil'), edit_message_path(@message) %> 
    </p>
    <div> 
        <%= button_to 'Удалить письмо', message_path(@message), method: :delete %>
    </div>
    <p class="mt"> <%= link_to "Вернуться ко всем отправленным письмам", messages_path%> </p>
</div>